Allow customisation of the keys that trigger insertation of a completion
AvaloniaUI/AvaloniaEdit pull request #358
Opened 2023-07-18 18:30 UTC by zenonet

Some people might not want to insert code completions using the enter key because they want to be able to create line breaks even when a completion window shows up. For example they might only want to insert completions using the tab key.

This PR adds a `Key[]` called `CompletionAcceptKeys` to the `CompletionList` Class. Now, when a keypress is handled by the completion list, it will check if the pressed key is is present in the CompletionAcceptKeys array instead of deciding based on the hard coded switch statement.

By default, this array will contain the Enter key and the tab key, so the behavior is unchanged.

2023-07-18 18:31 UTC, zenonet commented
@dotnet-policy-service agree

2023-07-19 10:17 UTC, danipen requested changes
LGTM. Thanks for the contribution. Can you please apply the requested changes just for code readability?

2023-07-19 10:17 UTC, danipen commented on src/AvaloniaEdit/CodeCompletion/CompletionList.cs
> +                    if (CompletionAcceptKeys.Contains(e.Key))
Can you group the two conditions in one using && to avoid 2-level nesting?

2023-07-19 12:47 UTC, zenonet commented
Done!

2023-07-19 13:10 UTC, danipen approved these changes
Looks good.

2023-07-19 13:10 UTC, merged